# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\maint_screen.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_maintenance_Dialog(object):
    def setupUi(self, maintenance_Dialog):
        maintenance_Dialog.setObjectName("maintenance_Dialog")
        maintenance_Dialog.resize(487, 383)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Alien.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        maintenance_Dialog.setWindowIcon(icon)
        maintenance_Dialog.setStyleSheet("QDialog{\n"
"    background-color: qconicalgradient(cx:0.8125, cy:0.761, angle:0, stop:0 rgba(191, 218, 15, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));}")
        self.sla_uptime = QtWidgets.QComboBox(maintenance_Dialog)
        self.sla_uptime.setGeometry(QtCore.QRect(40, 70, 281, 22))
        self.sla_uptime.setObjectName("sla_uptime")
        self.label = QtWidgets.QLabel(maintenance_Dialog)
        self.label.setGeometry(QtCore.QRect(150, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.back_code = QtWidgets.QLineEdit(maintenance_Dialog)
        self.back_code.setGeometry(QtCore.QRect(40, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_code.setFont(font)
        self.back_code.setAlignment(QtCore.Qt.AlignCenter)
        self.back_code.setObjectName("back_code")
        self.back_descr = QtWidgets.QLineEdit(maintenance_Dialog)
        self.back_descr.setGeometry(QtCore.QRect(200, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_descr.setFont(font)
        self.back_descr.setAlignment(QtCore.Qt.AlignCenter)
        self.back_descr.setObjectName("back_descr")
        self.start_date = QtWidgets.QDateEdit(maintenance_Dialog)
        self.start_date.setGeometry(QtCore.QRect(320, 190, 110, 22))
        self.start_date.setCalendarPopup(True)
        self.start_date.setDate(QtCore.QDate(2018, 1, 1))
        self.start_date.setObjectName("start_date")
        self.end_date = QtWidgets.QDateEdit(maintenance_Dialog)
        self.end_date.setGeometry(QtCore.QRect(320, 250, 110, 22))
        self.end_date.setCalendarPopup(True)
        self.end_date.setDate(QtCore.QDate(2019, 1, 1))
        self.end_date.setObjectName("end_date")
        self.label_2 = QtWidgets.QLabel(maintenance_Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 170, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(maintenance_Dialog)
        self.label_3.setGeometry(QtCore.QRect(340, 230, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(maintenance_Dialog)
        self.frame.setGeometry(QtCore.QRect(310, 170, 131, 121))
        self.frame.setStyleSheet("QFrame{background-color:rgb(188, 188, 188)}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(maintenance_Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 169, 251, 121))
        self.groupBox.setStyleSheet("QGroupBox{background-color: rgb(217, 217, 217);\n"
"    border-color: rgb(11, 11, 11);\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.list_back = QtWidgets.QLineEdit(self.groupBox)
        self.list_back.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.list_back.setFont(font)
        self.list_back.setAlignment(QtCore.Qt.AlignCenter)
        self.list_back.setObjectName("list_back")
        self.cost_back = QtWidgets.QLineEdit(self.groupBox)
        self.cost_back.setGeometry(QtCore.QRect(10, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cost_back.setFont(font)
        self.cost_back.setAlignment(QtCore.Qt.AlignCenter)
        self.cost_back.setObjectName("cost_back")
        self.uplift = QtWidgets.QLineEdit(self.groupBox)
        self.uplift.setGeometry(QtCore.QRect(170, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uplift.setFont(font)
        self.uplift.setAlignment(QtCore.Qt.AlignCenter)
        self.uplift.setObjectName("uplift")
        self.margin = QtWidgets.QLineEdit(self.groupBox)
        self.margin.setGeometry(QtCore.QRect(170, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.margin.setFont(font)
        self.margin.setAlignment(QtCore.Qt.AlignCenter)
        self.margin.setObjectName("margin")
        self.ok_button = QtWidgets.QPushButton(maintenance_Dialog)
        self.ok_button.setGeometry(QtCore.QRect(120, 310, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ok_button.setFont(font)
        self.ok_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.994, y1:0.869318, x2:1, y2:0, stop:0 rgba(172, 172, 172, 255), stop:1 rgba(227, 227, 227, 255));")
        self.ok_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok_button.setIcon(icon1)
        self.ok_button.setIconSize(QtCore.QSize(64, 64))
        self.ok_button.setObjectName("ok_button")
        self.label_4 = QtWidgets.QLabel(maintenance_Dialog)
        self.label_4.setGeometry(QtCore.QRect(366, 20, 81, 81))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/didata.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.clear_button = QtWidgets.QPushButton(maintenance_Dialog)
        self.clear_button.setGeometry(QtCore.QRect(270, 310, 91, 41))
        self.clear_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.994, y1:0.869318, x2:1, y2:0, stop:0 rgba(134, 150, 255, 255), stop:1 rgba(227, 227, 227, 255))")
        self.clear_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_button.setIcon(icon2)
        self.clear_button.setIconSize(QtCore.QSize(32, 32))
        self.clear_button.setObjectName("clear_button")
        self.frame.raise_()
        self.sla_uptime.raise_()
        self.label.raise_()
        self.back_code.raise_()
        self.back_descr.raise_()
        self.start_date.raise_()
        self.end_date.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.groupBox.raise_()
        self.ok_button.raise_()
        self.label_4.raise_()
        self.clear_button.raise_()
        self.label.setBuddy(self.sla_uptime)

        self.retranslateUi(maintenance_Dialog)
        QtCore.QMetaObject.connectSlotsByName(maintenance_Dialog)

    def retranslateUi(self, maintenance_Dialog):
        _translate = QtCore.QCoreApplication.translate
        maintenance_Dialog.setWindowTitle(_translate("maintenance_Dialog", "Datos de mantenimiento"))
        self.label.setText(_translate("maintenance_Dialog", "<html><head/><body><p>Uptime SLA</p></body></html>"))
        self.back_code.setPlaceholderText(_translate("maintenance_Dialog", "Código de backout"))
        self.back_descr.setPlaceholderText(_translate("maintenance_Dialog", "Descripción de backout"))
        self.label_2.setText(_translate("maintenance_Dialog", "<html><head/><body><p>Fecha de inicio</p></body></html>"))
        self.label_3.setText(_translate("maintenance_Dialog", "<html><head/><body><p>Fecha de fin</p></body></html>"))
        self.groupBox.setTitle(_translate("maintenance_Dialog", "Datos económicos"))
        self.list_back.setPlaceholderText(_translate("maintenance_Dialog", "Pr. lista backout"))
        self.cost_back.setPlaceholderText(_translate("maintenance_Dialog", "Coste backout"))
        self.uplift.setPlaceholderText(_translate("maintenance_Dialog", "Uplift"))
        self.margin.setPlaceholderText(_translate("maintenance_Dialog", "Margen"))

import icons_rc
