# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Oferta_Manual(object):
    def setupUi(self, Oferta_Manual):
        Oferta_Manual.setObjectName("Oferta_Manual")
        Oferta_Manual.resize(428, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Alien.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Oferta_Manual.setWindowIcon(icon)
        Oferta_Manual.setStyleSheet("QDialog{\n"
"    background-color: qconicalgradient(cx:0.8125, cy:0.761, angle:0, stop:0 rgba(191, 218, 15, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));}")
        self.manufacturer = QtWidgets.QComboBox(Oferta_Manual)
        self.manufacturer.setGeometry(QtCore.QRect(40, 80, 191, 21))
        self.manufacturer.setObjectName("manufacturer")
        self.code = QtWidgets.QLineEdit(Oferta_Manual)
        self.code.setGeometry(QtCore.QRect(140, 120, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.code.setFont(font)
        self.code.setStyleSheet("color:rgb(0, 0, 255)")
        self.code.setAlignment(QtCore.Qt.AlignCenter)
        self.code.setObjectName("code")
        self.description = QtWidgets.QLineEdit(Oferta_Manual)
        self.description.setGeometry(QtCore.QRect(40, 160, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setStyleSheet("color:rgb(0, 0, 255)")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.list_price = QtWidgets.QLineEdit(Oferta_Manual)
        self.list_price.setGeometry(QtCore.QRect(40, 200, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_price.setFont(font)
        self.list_price.setStyleSheet("color:rgb(0, 0, 255)")
        self.list_price.setAlignment(QtCore.Qt.AlignCenter)
        self.list_price.setObjectName("list_price")
        self.cost = QtWidgets.QLineEdit(Oferta_Manual)
        self.cost.setGeometry(QtCore.QRect(160, 200, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cost.setFont(font)
        self.cost.setStyleSheet("color:rgb(0, 0, 255)")
        self.cost.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.cost.setAlignment(QtCore.Qt.AlignCenter)
        self.cost.setObjectName("cost")
        self.margin = QtWidgets.QLineEdit(Oferta_Manual)
        self.margin.setGeometry(QtCore.QRect(280, 200, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.margin.setFont(font)
        self.margin.setStyleSheet("color:rgb(0, 0, 255)")
        self.margin.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.margin.setAlignment(QtCore.Qt.AlignCenter)
        self.margin.setObjectName("margin")
        self.maintenance = QtWidgets.QCheckBox(Oferta_Manual)
        self.maintenance.setGeometry(QtCore.QRect(190, 240, 101, 17))
        self.maintenance.setObjectName("maintenance")
        self.add_button = QtWidgets.QPushButton(Oferta_Manual)
        self.add_button.setGeometry(QtCore.QRect(100, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.994, y1:0.869318, x2:1, y2:0, stop:0 rgba(172, 172, 172, 255), stop:1 rgba(227, 227, 227, 255));")
        self.add_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon1)
        self.add_button.setIconSize(QtCore.QSize(32, 32))
        self.add_button.setObjectName("add_button")
        self.add_finish_button = QtWidgets.QPushButton(Oferta_Manual)
        self.add_finish_button.setGeometry(QtCore.QRect(230, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_finish_button.setFont(font)
        self.add_finish_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.994, y1:0.869318, x2:1, y2:0, stop:0 rgba(172, 172, 172, 255), stop:1 rgba(227, 227, 227, 255));")
        self.add_finish_button.setObjectName("add_finish_button")
        self.label = QtWidgets.QLabel(Oferta_Manual)
        self.label.setGeometry(QtCore.QRect(110, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.qty = QtWidgets.QLineEdit(Oferta_Manual)
        self.qty.setGeometry(QtCore.QRect(40, 120, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.qty.setFont(font)
        self.qty.setStyleSheet("color:rgb(0, 0, 255)")
        self.qty.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.qty.setAlignment(QtCore.Qt.AlignCenter)
        self.qty.setObjectName("qty")
        self.label_2 = QtWidgets.QLabel(Oferta_Manual)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 85, 255)")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.didata = QtWidgets.QLabel(Oferta_Manual)
        self.didata.setGeometry(QtCore.QRect(320, 30, 81, 81))
        self.didata.setText("")
        self.didata.setPixmap(QtGui.QPixmap(":/didata.png"))
        self.didata.setScaledContents(True)
        self.didata.setObjectName("didata")
        self.tech = QtWidgets.QComboBox(Oferta_Manual)
        self.tech.setGeometry(QtCore.QRect(250, 80, 51, 21))
        self.tech.setObjectName("tech")
        self.label_3 = QtWidgets.QLabel(Oferta_Manual)
        self.label_3.setGeometry(QtCore.QRect(260, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Oferta_Manual)
        QtCore.QMetaObject.connectSlotsByName(Oferta_Manual)

    def retranslateUi(self, Oferta_Manual):
        _translate = QtCore.QCoreApplication.translate
        Oferta_Manual.setWindowTitle(_translate("Oferta_Manual", "Generación de ofertas Direct"))
        self.code.setPlaceholderText(_translate("Oferta_Manual", "Código"))
        self.description.setPlaceholderText(_translate("Oferta_Manual", "Descripción"))
        self.list_price.setPlaceholderText(_translate("Oferta_Manual", "Precio de lista"))
        self.cost.setPlaceholderText(_translate("Oferta_Manual", "Coste"))
        self.margin.setPlaceholderText(_translate("Oferta_Manual", "Margen"))
        self.maintenance.setText(_translate("Oferta_Manual", "¿Mantenimiento?"))
        self.add_finish_button.setText(_translate("Oferta_Manual", "Generar \n"
" csv"))
        self.label.setText(_translate("Oferta_Manual", "Fabricante"))
        self.qty.setPlaceholderText(_translate("Oferta_Manual", "Unidades"))
        self.label_2.setText(_translate("Oferta_Manual", "Introducción de datos"))
        self.label_3.setText(_translate("Oferta_Manual", "<html><head/><body><p>Tech</p></body></html>"))

import icons_rc
